# llm/llm_call.py
from __future__ import annotations

import json
import os
import textwrap
from pathlib import Path
from typing import Optional

import pandas as pd


def _safe_markdown_table(df: pd.DataFrame, max_rows: int = 12) -> str:
    if not isinstance(df, pd.DataFrame) or df.empty:
        return "_No similarity rows available._"

    tmp = df.copy().head(max_rows)

    max_cols = 12
    if tmp.shape[1] > max_cols:
        keep_cols = list(tmp.columns[:max_cols])
        tmp = tmp[keep_cols]

    for c in tmp.columns:
        tmp[c] = tmp[c].apply(
            lambda x: x if isinstance(x, (int, float, str, bool)) or pd.isna(x) else str(x)
        )

    try:
        return tmp.to_markdown(index=False)
    except Exception:
        return tmp.to_string(index=False)


def _numeric_summary(df: pd.DataFrame) -> str:
    if not isinstance(df, pd.DataFrame) or df.empty:
        return "No numeric summary available."

    lines = []

    preferred = [
        "similarity",
        "pred",
        "score",
        "weight",
        "label_next_month_ret",
        "label_next_month_mdd",
    ]

    cols = [c for c in preferred if c in df.columns]
    cols += [c for c in df.select_dtypes(include=["number"]).columns if c not in cols]
    cols = cols[:10]

    if not cols:
        return "No numeric columns found in pred_df."

    for c in cols:
        s = pd.to_numeric(df[c], errors="coerce").dropna()
        if len(s) == 0:
            continue
        lines.append(
            f"- {c}: mean={s.mean():.4f}, std={s.std():.4f}, "
            f"min={s.min():.4f}, median={s.median():.4f}, max={s.max():.4f}"
        )

    return "\n".join(lines) if lines else "No numeric summary available."


def build_market_prompt(pred_df: pd.DataFrame) -> str:
    table_md = _safe_markdown_table(pred_df, max_rows=12)
    stats_txt = _numeric_summary(pred_df)

    prompt = f"""
You are a quantitative market analyst.

A similarity-based market regime retrieval system has produced the following rows.
These rows summarize historically similar market situations and/or predictions.

## Retrieved Similarity Table
{table_md}

## Numeric Summary
{stats_txt}

Please write a concise markdown report with exactly these sections:

## Market Commentary
2-4 sentences describing what the retrieved results suggest.

## Evidence
3-5 bullet points using only the information visible in the table/summary.

## Interpretation
2-4 sentences on what this may imply for market conditions or portfolio positioning.

Rules:
- Be concrete and professional.
- Do not invent columns or metrics not shown above.
- If evidence is limited, say so explicitly.
- Do not mention hidden reasoning.
"""
    return textwrap.dedent(prompt).strip()


def _fallback_report(pred_df: pd.DataFrame) -> str:
    n_rows = len(pred_df) if isinstance(pred_df, pd.DataFrame) else 0
    cols = list(pred_df.columns)[:12] if isinstance(pred_df, pd.DataFrame) else []

    sim_msg = ""
    if isinstance(pred_df, pd.DataFrame) and "similarity" in pred_df.columns:
        s = pd.to_numeric(pred_df["similarity"], errors="coerce").dropna()
        if len(s) > 0:
            sim_msg = (
                f"The average retrieved similarity is {s.mean():.4f}, "
                f"with a maximum of {s.max():.4f}. "
            )

    numeric_summary = _numeric_summary(pred_df) if isinstance(pred_df, pd.DataFrame) else "No numeric summary."

    return textwrap.dedent(
        f"""
        ## Market Commentary

        The similarity-based retrieval pipeline returned {n_rows} rows. {sim_msg}
        This report is generated by the local fallback path because no external LLM backend was configured.

        ## Evidence

        - Available columns: {", ".join(cols) if cols else "None"}.
        - The report used the retrieved similarity dataframe directly.
        - No external model call was made in this fallback mode.

        ## Interpretation

        The quant pipeline is working and producing structured retrieval output.
        To enable true LLM generation, configure either OpenAI or Ollama as described in the code comments.
        
        ## Numeric Summary

        {numeric_summary}
        """
    ).strip()


def _call_openai(prompt: str, model: Optional[str] = None) -> Optional[str]:
    api_key = os.getenv("OPENAI_API_KEY")
    if not api_key:
        return None

    try:
        from openai import OpenAI
    except Exception:
        return None

    model = model or os.getenv("OPENAI_MODEL", "gpt-4.1-mini")

    try:
        client = OpenAI(api_key=api_key)
        resp = client.responses.create(
            model=model,
            input=prompt,
        )
        text = getattr(resp, "output_text", None)
        if text and text.strip():
            return text.strip()
        return None
    except Exception:
        return None


def _call_ollama(prompt: str, model: Optional[str] = None) -> Optional[str]:
    import urllib.error
    import urllib.request

    model = model or os.getenv("OLLAMA_MODEL")
    if not model:
        return None

    host = os.getenv("OLLAMA_HOST", "http://127.0.0.1:11434")
    url = f"{host.rstrip('/')}/api/generate"

    payload = {
        "model": model,
        "prompt": prompt,
        "stream": False,
    }

    req = urllib.request.Request(
        url,
        data=json.dumps(payload).encode("utf-8"),
        headers={"Content-Type": "application/json"},
        method="POST",
    )

    try:
        with urllib.request.urlopen(req, timeout=120) as resp:
            data = json.loads(resp.read().decode("utf-8"))
            text = data.get("response", "")
            return text.strip() if text else None
    except (urllib.error.URLError, urllib.error.HTTPError, TimeoutError, Exception):
        return None


def explain_similarity_with_llm(
    pred_df: pd.DataFrame,
    output_dir: str = "llm",
    model: Optional[str] = None,
) -> str:
    """
    Writes:
      - llm/prompt.txt
      - llm/final.md

    Behavior:
      1) Try OpenAI if OPENAI_API_KEY exists
      2) Else try Ollama if OLLAMA_MODEL exists
      3) Else fallback to deterministic local report
    """
    out = Path(output_dir)
    out.mkdir(parents=True, exist_ok=True)

    if not isinstance(pred_df, pd.DataFrame):
        pred_df = pd.DataFrame(pred_df)

    prompt = build_market_prompt(pred_df)
    (out / "prompt.txt").write_text(prompt, encoding="utf-8")

    result = _call_openai(prompt, model=model)
    backend = "openai" if result else None

    if result is None:
        result = _call_ollama(prompt, model=model)
        backend = "ollama" if result else None

    if result is None:
        result = _fallback_report(pred_df)
        backend = "fallback"

    final_text = f"<!-- backend: {backend} -->\n\n{result}".strip()
    (out / "final.md").write_text(final_text, encoding="utf-8")

    return final_text
